# Generated by Django 3.1.3 on 2020-11-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catetegores',
            new_name='categories',
        ),
    ]
